require('./register-tests.cjs');const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),ts=require('./app/node_modules/typescript');const Q=require('./app/src/quantities.ts'),E=require('./app/src/engine.ts'),{calculate}=require('./app/src/planning.ts');
test('mg/mcg quantities are equivalent through conversion, editing and calculation',()=>{for(const [mcg,mg]of [[200,.2],[500,.5],[1000,1]]){assert.equal(Q.toMg({value:mcg,unit:'mcg'}),mg);assert.deepEqual(calculate('10','2',String(Q.toMg({value:mcg,unit:'mcg'}))),calculate('10','2',String(Q.toMg({value:mg,unit:'mg'}))));assert.equal(E.storedAmount(String(mcg),'mcg'),String(mg));assert.equal(Q.quantityLabel(Q.quantityFromMg(mg,'mcg')),mcg+' mcg')}assert.throws(()=>Q.toMg({value:2,unit:'g'}));});
test('syringe automatic scales and markers map exactly to selected capacities',()=>{for(const [draw,capacity,x]of [[4,30,66],[25,30,255],[40,50,246],[75,100,232.5]]){const s=Q.syringeScale(draw);assert.equal(s.capacity,capacity);assert.equal(s.x,x);assert.equal(s.exceeds,false)}assert.equal(Q.syringeScale(4,100).x,40.8);assert.equal(Q.syringeScale(40,30).x,300);assert.equal(Q.syringeScale(40,30).exceeds,true);assert.equal(Q.syringeScale(101).exceeds,true);assert.equal(Q.syringeScale(NaN).x,30);});
test('installed SVG parser reproduces the old warning and accepts every repaired gradient stop',()=>{
 const source=fs.readFileSync('./app/node_modules/react-native-svg/src/lib/extract/extractGradient.ts','utf8');const part=source.slice(source.indexOf('const percentReg'),source.indexOf('const offsetComparator'));const code=ts.transpileModule(part,{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText;const warnings=[];const parse=vm.runInNewContext(code+';percentToFloat',{console:{warn:m=>warnings.push(m)}});
 assert.equal(parse('.5'),0);assert.match(warnings[0],/not a valid number or percentage/);warnings.length=0;
 const svg=fs.readFileSync('./app/src/Syringe.tsx','utf8');const stops=[...svg.matchAll(/offset=(?:"([^"]+)"|\{([^}]+)\})/g)].map(m=>m[1]??Number(m[2]));assert.equal(stops.length,7);assert.deepEqual(stops.map(parse),[0,.3,.8,1,0,.5,1]);assert.deepEqual(warnings,[]);assert.ok(!/="\.[0-9]/.test(svg));
});
test('legacy saved stage/event units are upgraded without changing mg values or event status',()=>{const c=require('./app/src/content.ts').compounds.find(c=>c.id==='kpv'),d=E.importReference(c);Object.assign(d,{reviewed:true,startDate:'2026-09-07',breakWeeks:'0'});const plan=E.activate(d);delete plan.events[0].amountUnit;delete plan.stages[1].amountUnit;const read=E.decodeStore(JSON.stringify({...E.blankStore(),active:plan}));assert.equal(read.active.events[0].amountUnit,'mcg');assert.equal(read.active.events[0].amountMg,.2);assert.equal(read.active.stages[1].amountUnit,'mg');assert.equal(read.active.stages[1].amountMg,'0.3');});
