require('./register-tests.cjs');const test=require('node:test'),assert=require('node:assert/strict');const E=require('./app/src/engine.ts'),{compounds}=require('./app/src/content.ts'),{calculate}=require('./app/src/planning.ts'),{syringeScale}=require('./app/src/quantities.ts');
const expected={'retatrutide':[10,2,5,50],'tirzepatide':[10,2,5,50],'semaglutide':[10,2,5,30],'kpv':[10,2,5,30],'ghk-cu':[50,3,50/3,30],'glow-70':[70,3,70/3,30]};
for(const [id,[vial,water,concentration,capacity]]of Object.entries(expected))test(id+' source + common setup transfer and persistence',()=>{
 const c=compounds.find(c=>c.id===id),t=c.school.referenceSchedules[0],d=E.importReference(c,t);const source=t?t.suppliedPlan:c.supplied.commonResearchPractice;
 assert.deepEqual(d.origin.originalReference,source);assert.deepEqual(d.origin.originalStages,source.stages);assert.equal(d.vialMg,String(vial));assert.equal(d.waterMl,String(water));assert.deepEqual(d.defaultSchedule.times,['09:00']);assert.equal(calculate(d.vialMg,d.waterMl,d.stages[0].amountMg).concentration,concentration);assert.equal(d.setupOrigin.sourceClass,'Common Research Setup');assert.equal(d.setupOrigin.original.defaultSyringeCapacityUnits,capacity);assert.ok(d.stages.every(s=>s.amountMg&&s.weeks&&['mg','mcg'].includes(s.amountUnit)));
 if(t)assert.equal(d.origin.originalReference.vialStrengthMg,undefined);
 const original=structuredClone(d.origin),setup=structuredClone(d.setupOrigin.original);let edited=E.editDraft(d,{vialMg:String(vial*2),waterMl:'4',syringeCapacityUnits:100},false);assert.equal(edited.customized,false);assert.equal(edited.setupOrigin.customized,true);assert.deepEqual(edited.origin,original);assert.deepEqual(edited.setupOrigin.original,setup);
 edited=E.editDraft(edited,{stages:edited.stages.map((s,i)=>i===0?{...s,amountMg:'1'}:s)},true);assert.equal(edited.customized,true);assert.deepEqual(edited.origin,original);
 const plan=E.activate({...d,reviewed:true,startDate:'2026-09-07',breakWeeks:d.breakWeeks||'0',syringeCapacityUnits:100});assert.equal(plan.initialVials,'');assert.equal(plan.inventoryTotalMg,null);assert.deepEqual(E.decodeStore(JSON.stringify({...E.blankStore(),active:plan})).active,plan);assert.equal(plan.syringeCapacityUnits,100);assert.equal(syringeScale(plan.events[0].calculation.units,plan.syringeCapacityUnits).capacity,100);
 if(id==='glow-70')assert.deepEqual(plan.blendComposition,[{component:'GHK-Cu',amountMg:50},{component:'BPC-157',amountMg:10},{component:'TB-500',amountMg:10}]);
});
test('unconfigured custom plan retains missing choices and does not calculate or start',()=>{const d=E.newDraft(compounds[0]);assert.equal(d.vialMg,'');assert.equal(d.waterMl,'');assert.equal(calculate(d.vialMg,d.waterMl,''),null);assert.throws(()=>E.activate(d));});
