import React,{useEffect,useRef,useState} from 'react';
import {ScrollView,Text,View,Pressable,StyleSheet,AppState} from 'react-native';
import type {Store,SavedPlan,Event} from './engine';
import {localDate,parseDate,prettyDate,prettyTime,eventStatus,logEvent,stageAmount} from './engine';
import {aggregateEvents,eventsForDay,replacePlan,getActivePlans} from './multiplan-v04';
import {Button,Card,u} from './ui';
import Syringe from './Syringe';
import {quantityFromMg} from './quantities';
export default function AggregateTracker({plans,archives,update,initialTab='Today',onOpen}:{plans:SavedPlan[];archives:SavedPlan[];update:(f:(s:Store)=>Store)=>Promise<void>;initialTab?:string;onOpen:(id:string)=>void}){
 const [tab,setTab]=useState(initialTab),[now,setNow]=useState(new Date()),[selected,setSelected]=useState(localDate()),[month,setMonth]=useState(localDate().slice(0,7)+'-01'),[expanded,setExpanded]=useState<string|null>(null),[limit,setLimit]=useState(30),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const locked=useRef(false);
 useEffect(()=>{const refresh=()=>setNow(new Date());const timer=setInterval(refresh,30000),sub=AppState.addEventListener('change',state=>{if(state==='active')refresh();});return()=>{clearInterval(timer);sub.remove();};},[]);
 const all=aggregateEvents(plans),today=localDate(now),todayRows=all.filter(x=>x.event.localDate===today);
 const nextRows=all.filter(x=>x.event.status==='pending'&&new Date(x.event.scheduledAt)>now).slice(0,3);
 const completedToday=todayRows.filter(x=>x.event.status==='completed').length;
 const history=aggregateEvents([...archives,...plans]).filter(x=>x.event.status!=='pending').sort((a,b)=>(b.event.completedAt??b.event.skippedAt??b.event.scheduledAt).localeCompare(a.event.completedAt??a.event.skippedAt??a.event.scheduledAt));
 const pendingPast=all.filter(x=>x.event.status==='pending'&&x.event.localDate<today);
 const action=async(planId:string,eventId:string,value:'completed'|'skipped'|'later')=>{if(locked.current)return;locked.current=true;setBusy(true);try{await update(s=>{const p=getActivePlans(s).find(p=>p.id===planId);return p?replacePlan(s,logEvent(p,eventId,value,new Date())):s;});setError('');setMessage(value==='later'?'Reminder moved 15 minutes later.':'Event saved.');}catch(e){setError(String(e));}finally{locked.current=false;setBusy(false);}};
 const eventCard=({plan,event:e}:{plan:SavedPlan;event:Event})=>{const key=plan.id+':'+e.id,isActive=plans.some(p=>p.id===plan.id),status=eventStatus(e,now);return <Card key={key}><View style={s.eventHead}><View style={[s.compoundDot,{backgroundColor:compoundColor(plan.compoundId)}]}/><View style={{flex:1}}><Text style={u.heading}>{plan.compoundName}</Text><Text style={u.small}>{prettyTime(e.scheduledAt)} · Stage {e.stageIndex+1}</Text></View><Text style={[s.status,{color:colors[status]}]}>{status}</Text></View><Text style={u.body}>{stageAmount({amountMg:String(e.amountMg),amountUnit:e.amountUnit})} · {Number(e.calculation.units.toFixed(3))} units</Text>{e.completedAt&&<Text style={u.small}>Completed {new Date(e.completedAt).toLocaleString()}</Text>}{e.skippedAt&&<Text style={u.small}>Skipped {new Date(e.skippedAt).toLocaleString()}</Text>}<Pressable accessibilityRole="button" accessibilityLabel={'Event details '+plan.compoundName+' '+e.id} accessibilityState={{expanded:expanded===key}} onPress={()=>setExpanded(expanded===key?null:key)}><Text style={u.link}>{expanded===key?'Hide details':'Calculation & details'} {expanded===key?'−':'+'}</Text></Pressable>{expanded===key&&<><Syringe result={e.calculation} amount={quantityFromMg(e.amountMg,e.amountUnit)} glow={plan.compoundId==='glow-70'} capacityOverride={plan.syringeCapacityUnits??null} onCapacityChange={size=>{if(isActive)update(s=>{const p=getActivePlans(s).find(p=>p.id===plan.id);return p?replacePlan(s,{...p,syringeCapacityUnits:size}):s;}).catch(err=>setError(String(err)));}}/>{isActive&&<Button label={'Open '+plan.compoundName+' plan'} secondary onPress={()=>onOpen(plan.id)}/>}</>}{isActive&&e.status==='pending'&&new Date(e.scheduledAt)<=now&&<><Button label="Completed" accessibilityLabel={'Complete '+plan.compoundName+' '+prettyTime(e.scheduledAt)} disabled={busy} onPress={()=>action(plan.id,e.id,'completed')}/><View style={u.row}><Button label="Skip" accessibilityLabel={'Skip '+plan.compoundName+' '+prettyTime(e.scheduledAt)} secondary disabled={busy} onPress={()=>action(plan.id,e.id,'skipped')}/><Button label="Remind later" accessibilityLabel={'Remind later '+plan.compoundName+' '+prettyTime(e.scheduledAt)} secondary disabled={busy} onPress={()=>action(plan.id,e.id,'later')}/></View></>}</Card>;};
 const monthDate=parseDate(month)!,count=new Date(monthDate.getFullYear(),monthDate.getMonth()+1,0).getDate(),leading=(monthDate.getDay()+6)%7;
 const move=(amount:number)=>{const d=parseDate(month)!;d.setMonth(d.getMonth()+amount);setMonth(localDate(d));};
 return <ScrollView contentContainerStyle={u.scroll}><View style={s.hero}><Text style={s.kicker}>TRACKER</Text><Text style={s.heroTitle}>Today at a glance</Text><Text style={s.heroSub}>{plans.length} active {plans.length===1?'plan':'plans'} · one timeline</Text><View style={s.metrics}><View style={s.metric}><Text style={s.metricBig}>{todayRows.length}</Text><Text style={s.metricSmall}>Today</Text></View><View style={s.metric}><Text style={s.metricBig}>{completedToday}</Text><Text style={s.metricSmall}>Completed</Text></View><View style={s.metric}><Text style={s.metricBig}>{pendingPast.length}</Text><Text style={s.metricSmall}>Needs log</Text></View></View></View>
 <View style={s.tabs}>{['Today','Calendar','History'].map(name=><Pressable key={name} accessibilityRole="tab" accessibilityLabel={name} accessibilityState={{selected:tab===name}} onPress={()=>{setTab(name);setLimit(30);}} style={[s.tab,tab===name&&s.tabSelected]}><Text style={[s.tabText,tab===name&&s.tabTextSelected]}>{name}</Text></Pressable>)}</View>
 {!!error&&<Text style={u.error}>{error}</Text>}{!!message&&<Text accessibilityLiveRegion="polite" style={u.small}>{message}</Text>}
 {tab==='Today'&&<><Text style={[u.heading,{marginTop:18}]}>{prettyDate(today)}</Text>{todayRows.map(eventCard)}{!todayRows.length&&<Card><Text style={u.heading}>Nothing scheduled today</Text><Text style={u.body}>Your next scheduled items will appear here automatically.</Text></Card>}{pendingPast.length>0&&<Card><Text style={u.heading}>Earlier items need a log</Text><Text style={u.body}>{pendingPast.length} scheduled {pendingPast.length===1?'event is':'events are'} still unlogged.</Text><Button label="Review earlier events" secondary onPress={()=>{setSelected(pendingPast[0].event.localDate);setMonth(pendingPast[0].event.localDate.slice(0,7)+'-01');setTab('Calendar');}}/></Card>}{nextRows.length>0&&<View style={s.upNext}><Text style={u.heading}>Up next</Text>{nextRows.map(({plan,event})=><Pressable key={plan.id+event.id} accessibilityRole="button" onPress={()=>{setSelected(event.localDate);setMonth(event.localDate.slice(0,7)+'-01');setTab('Calendar');}} style={s.nextRow}><View style={[s.compoundDot,{backgroundColor:compoundColor(plan.compoundId)}]}/><View style={{flex:1}}><Text style={s.nextName}>{plan.compoundName}</Text><Text style={u.small}>{prettyDate(event.localDate)} · {prettyTime(event.scheduledAt)}</Text></View><Text style={s.arrow}>›</Text></Pressable>)}</View>}</>}
 {tab==='Calendar'&&<><View style={[u.row,{justifyContent:'space-between',marginTop:18}]}><Pressable accessibilityRole="button" accessibilityLabel="Previous month" onPress={()=>move(-1)} style={s.monthArrow}><Text style={s.arrow}>‹</Text></Pressable><Text style={u.heading}>{monthDate.toLocaleDateString(undefined,{month:'long',year:'numeric'})}</Text><Pressable accessibilityRole="button" accessibilityLabel="Next month" onPress={()=>move(1)} style={s.monthArrow}><Text style={s.arrow}>›</Text></Pressable></View><View style={s.grid}>{['M','T','W','T','F','S','S'].map((d,i)=><Text key={i} style={s.weekday}>{d}</Text>)}{Array.from({length:leading},(_,i)=><View key={'b'+i} style={s.cell}/>)}{Array.from({length:count},(_,i)=>{const day=month.slice(0,8)+String(i+1).padStart(2,'0'),rows=all.filter(x=>x.event.localDate===day);return <Pressable key={day} accessibilityRole="button" accessibilityLabel={'Calendar '+day+', '+rows.length+' events'} accessibilityState={{selected:selected===day}} onPress={()=>setSelected(day)} style={[s.cell,day===selected&&s.selected]}><Text style={s.day}>{i+1}</Text>{rows.length>0&&<Text style={s.count}>{rows.length}</Text>}</Pressable>;})}</View><Text style={u.small}>The number on each date is the total across every active plan. Tap a date for details.</Text><Text style={[u.heading,{marginTop:18}]}>{prettyDate(selected)}</Text>{eventsForDay(plans,selected).map(eventCard)}{!eventsForDay(plans,selected).length&&<Text style={u.body}>No events on this day.</Text>}</>}
 {tab==='History'&&<><Text style={[u.body,{marginTop:18}]}>Completed and skipped events stay attached to their compound, including archived plans.</Text>{history.slice(0,limit).map(eventCard)}{!history.length&&<Card><Text style={u.body}>No completed or skipped events yet.</Text></Card>}{history.length>limit&&<Button label="Show more history" secondary onPress={()=>setLimit(n=>n+30)}/>}</>}
 </ScrollView>;
}
const colors={Completed:'#178066',Scheduled:'#076eac',Missed:'#bd4352',Future:'#7a65b2',Skipped:'#737b87'};
const compoundColor=(id:string)=>({'retatrutide':'#2FA9FF','tirzepatide':'#7C5CFF','semaglutide':'#3A8DFF','ghk-cu':'#22B7C8','kpv':'#6F6BFF','ss-31':'#18A0AE','mots-c':'#2FA9FF','nad-plus':'#7C5CFF','5-amino-1mq':'#5A67D8'} as Record<string,string>)[id]||'#27B9EE';
const s=StyleSheet.create({hero:{borderRadius:24,padding:18,backgroundColor:'#f4fbff',borderWidth:1,borderColor:'#dceaf5'},kicker:{fontSize:11,fontWeight:'800',letterSpacing:1.4,color:'#169ed0'},heroTitle:{fontSize:27,lineHeight:33,fontWeight:'800',color:'#10204a',marginTop:6},heroSub:{fontSize:13,color:'#61728f',marginTop:3},metrics:{flexDirection:'row',gap:8,marginTop:16},metric:{flex:1,borderRadius:14,paddingVertical:10,alignItems:'center',backgroundColor:'#fff'},metricBig:{fontSize:21,fontWeight:'800',color:'#10204a'},metricSmall:{fontSize:10,color:'#61728f',marginTop:2},tabs:{flexDirection:'row',gap:5,marginTop:14},tab:{flex:1,minWidth:0,paddingVertical:12,borderRadius:13,backgroundColor:'#f2f6fc',alignItems:'center'},tabSelected:{backgroundColor:'#dff6ff',borderWidth:1,borderColor:'#19b3e3'},tabText:{fontSize:14,fontWeight:'700',color:'#667597'},tabTextSelected:{color:'#10204a'},eventHead:{flexDirection:'row',alignItems:'center',gap:9},compoundDot:{width:10,height:10,borderRadius:5},status:{fontSize:11,fontWeight:'800',textTransform:'uppercase'},upNext:{marginTop:18},nextRow:{flexDirection:'row',alignItems:'center',gap:10,paddingVertical:12,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:'#dce6f2'},nextName:{fontSize:14,fontWeight:'800',color:'#10204a'},monthArrow:{width:44,height:44,alignItems:'center',justifyContent:'center'},arrow:{fontSize:28,color:'#067da7'},grid:{flexDirection:'row',flexWrap:'wrap',marginTop:12},weekday:{width:'14.2857%',textAlign:'center',color:'#61728f',paddingVertical:8},cell:{width:'14.2857%',height:62,alignItems:'center',justifyContent:'center',borderRadius:10},selected:{backgroundColor:'#dff6ff',borderWidth:1,borderColor:'#19b3e3'},day:{fontSize:16,color:'#18305c'},count:{fontSize:10,fontWeight:'700',color:'#076eac',backgroundColor:'#eaf9ff',borderRadius:8,paddingHorizontal:5,marginTop:4}});
