export type DeepSection={title:string;body:string};
export type V04LibraryEntry={
 id:string;name:string;aliases:string[];kind:string;accent:string;
 summary:string;plainEnglish:string;evidence:string;studiedFor:string;mechanism:string;
 deeper:DeepSection[];referenceMode:'existing'|'custom-only'; sources?:{id:string;title:string;type:string;url:string}[];
};

// 0.4 additions are intentionally educational/contextual. Study-specific human
// administration is kept distinct from community/common-practice conventions.
export const addedLibraryV04:V04LibraryEntry[]=[
 {id:'bpc-157',name:'BPC-157',aliases:['bpc157','bpc 157'],kind:'Experimental peptide',accent:'#20A486',referenceMode:'custom-only',
  summary:'BPC-157 is an experimental peptide investigated mainly in laboratory and animal models of tissue injury. Human evidence remains extremely limited.',
  plainEnglish:'Most claims come from preclinical research. A two-person intravenous pilot cannot establish effectiveness, routine subcutaneous use or a general dosing plan.',
  sources:[{id:'BPC-IV-2025',title:'Safety of Intravenous Infusion of BPC157 in Humans: A Pilot Study',type:'Human pilot research',url:'https://pubmed.ncbi.nlm.nih.gov/40131143/'},{id:'BPC-TENDON-2011',title:'BPC 157 and growth hormone receptor expression in tendon fibroblasts',type:'Preclinical research',url:'https://pubmed.ncbi.nlm.nih.gov/21030672/'}],
  evidence:'Two-person human intravenous pilot plus predominantly preclinical research; no established subcutaneous schedule.',studiedFor:'Tissue-repair mechanisms, tendon-cell signaling, angiogenesis and gastrointestinal injury models.',mechanism:'Proposed effects on cell migration and repair signaling remain largely preclinical.',
  deeper:[{title:'Human research',body:'A 2025 pilot exposed two healthy adults to intravenous BPC-157 and assessed short-term safety and pharmacokinetics. It was far too small to establish efficacy or a routine schedule.'},{title:'Preclinical research',body:'Cell and animal studies examine tendon fibroblasts, angiogenic signaling and injury models. These findings cannot be assumed to predict clinical benefit.'},{title:'Route and planning limits',body:'Intravenous pilot data do not validate subcutaneous research-vial conventions. PepPlan supplies no amount, frequency, vial setup or transferable reference.'}]},
 {id:'tb-500',name:'TB-500 / Thymosin beta-4',aliases:['tb500','tb 500','thymosin beta 4'],kind:'Research peptide',accent:'#E06A9A',referenceMode:'custom-only',
  summary:'Thymosin beta-4 is an endogenous actin-binding peptide studied in repair biology. Products called TB-500 require identity and formulation distinction.',
  plainEnglish:'Human wound studies used topical thymosin beta-4. They do not establish that a research vial sold as TB-500 is equivalent or supports an injectable schedule.',
  sources:[{id:'TB4-ULCER-2007',title:'Thymosin beta-4 and venous ulcers: a prospective randomized study',type:'Published human topical research',url:'https://pubmed.ncbi.nlm.nih.gov/17495250/'},{id:'TB4-WOUND-1999',title:'Thymosin beta4 accelerates wound healing',type:'Preclinical research',url:'https://pubmed.ncbi.nlm.nih.gov/10469335/'}],
  evidence:'Human topical wound research plus preclinical evidence; not equivalent to routine subcutaneous TB-500 use.',studiedFor:'Actin dynamics, cell migration, inflammation and wound-repair biology.',mechanism:'Thymosin beta-4 binds actin and has been studied in migration, angiogenesis and repair signaling.',
  deeper:[{title:'Human research',body:'A double-blind, placebo-controlled dose-escalation study evaluated topical thymosin beta-4 in venous ulcers. Route, formulation and population remain attached to the result.'},{title:'Preclinical research',body:'Animal wound models reported repair effects after topical or intraperitoneal thymosin beta-4, not an established human injectable regimen.'},{title:'Identity and planning limits',body:'TB-500 naming is inconsistent in research-product markets. PepPlan supplies no injectable amount, schedule or reconstitution default.'}]},
 {id:'ipamorelin',name:'Ipamorelin',aliases:['ipa','ipamorelin acetate'],kind:'Growth-hormone secretagogue research peptide',accent:'#4F86F7',referenceMode:'custom-only',
  summary:'Ipamorelin is a growth-hormone secretagogue studied in early human pharmacokinetic and pharmacodynamic research.',
  plainEnglish:'Human studies show biological activity, but early controlled intravenous research does not define a routine subcutaneous research-vial plan.',
  sources:[{id:'IPA-PKPD-1999',title:'Pharmacokinetic-pharmacodynamic modeling of ipamorelin in human volunteers',type:'Published human clinical research',url:'https://pubmed.ncbi.nlm.nih.gov/10496658/'},{id:'IPA-PK-1998',title:'Pharmacokinetic evaluation of ipamorelin in humans',type:'Published human pharmacokinetic research',url:'https://pubmed.ncbi.nlm.nih.gov/9879640/'}],
  evidence:'Early human intravenous PK/PD research; no approved or universal subcutaneous schedule.',studiedFor:'Growth-hormone release, dose-response behavior and early pharmacokinetics.',mechanism:'Ipamorelin acts as a ghrelin-receptor agonist and growth-hormone secretagogue.',
  deeper:[{title:'Human research',body:'Healthy-volunteer studies characterized intravenous pharmacokinetics and growth-hormone responses. They establish biological activity, not a general wellness protocol.'},{title:'Route and safety limits',body:'Intravenous data cannot be silently converted into a subcutaneous amount, frequency or syringe calculation. Long-term benefit and safety remain unestablished.'},{title:'Planning context',body:'No reference transfers until a route-matched reviewed source supports every prefilled field.'}]},
 {id:'tesamorelin',name:'Tesamorelin',aliases:['egrifta','th9507'],kind:'Growth-hormone-releasing factor analogue',accent:'#7B61E8',referenceMode:'custom-only',
  summary:'Tesamorelin has approved-product and randomized human evidence in a specific HIV-associated lipodystrophy context.',
  plainEnglish:'This evidence is stronger than for many research peptides, but indication, monitoring and product formulation matter. A research vial is not automatically interchangeable.',
  sources:[{id:'TESA-PHASE3-2010',title:'Effects of tesamorelin in HIV-infected patients with abdominal fat accumulation',type:'Published randomized human clinical research',url:'https://pubmed.ncbi.nlm.nih.gov/20101189/'},{id:'TESA-LIVER-2014',title:'Effect of tesamorelin on visceral fat and liver fat',type:'Published randomized human clinical research',url:'https://pubmed.ncbi.nlm.nih.gov/25038357/'}],
  evidence:'Approved-product context and randomized human subcutaneous research in a specific population; formulation-specific.',studiedFor:'Excess visceral abdominal fat in adults with HIV-associated lipodystrophy.',mechanism:'A stabilized growth-hormone-releasing factor analogue that stimulates pituitary growth hormone and downstream IGF-1.',
  deeper:[{title:'Human research',body:'Randomized trials in adults with HIV-associated abdominal fat accumulation found reductions in visceral adipose tissue over months. Findings belong to that population and monitored setting.'},{title:'Safety and formulation limits',body:'Evidence does not establish general weight-loss use. Glucose, IGF-1 and other monitoring considerations matter, and approved products have formulation-specific instructions.'},{title:'Planning context',body:'No research-vial setup is prefilled. A future labelled reference must identify jurisdiction and exact product formulation.'}]},
 {id:'cagrilintide',name:'Cagrilintide',aliases:['cagri','AM833'],kind:'Long-acting amylin analogue',accent:'#F07B3F',referenceMode:'custom-only',
  summary:'Cagrilintide is a long-acting amylin analogue studied in randomized clinical trials for weight management, alone and with semaglutide.',
  plainEnglish:'It has meaningful human dose-ranging evidence, but an investigational trial schedule is not an approved clinical recommendation.',
  sources:[{id:'CAGRI-P2-2021',title:'Once-weekly cagrilintide for weight management',type:'Published phase 2 randomized human clinical research',url:'https://pubmed.ncbi.nlm.nih.gov/34798060/'},{id:'CAGRI-COMBO-2021',title:'Coadministered cagrilintide and semaglutide: phase 1b trial',type:'Published phase 1b randomized human clinical research',url:'https://pubmed.ncbi.nlm.nih.gov/33894838/'}],
  evidence:'Published randomized human clinical research; investigational schedules are not approved recommendations.',studiedFor:'Weight management, appetite regulation and combination research with GLP-1 receptor agonists.',mechanism:'A long-acting amylin analogue designed to engage satiety pathways and influence energy intake.',
  deeper:[{title:'Key study',body:'A multicentre phase 2 trial randomized adults with overweight or obesity to weekly dose groups, liraglutide or placebo for 26 weeks and found dose-dependent weight change.'},{title:'Combination research',body:'A phase 1b trial studied coadministration with semaglutide using sequential escalation. It does not prove independently sourced mixtures or stacks are equivalent.'},{title:'Safety and planning limits',body:'Gastrointestinal events, eligibility, escalation, monitoring and manufactured formulation constrain interpretation. No regimen transfers until the complete staged reference is reviewed.'}]},
 {id:'5-amino-1mq',name:'5-Amino-1MQ',aliases:['5 amino 1mq','5amino1mq','1mq'],kind:'Small-molecule research compound',accent:'#5A67D8',referenceMode:'custom-only',
  summary:'5-Amino-1MQ is a small-molecule NNMT inhibitor used in metabolic research. It is not itself a peptide.',
  plainEnglish:'This belongs in the same tracker because people often research it alongside peptides, but the chemistry and evidence category are different.',
  evidence:'Preclinical research; no established human dosing schedule in this library.',studiedFor:'NNMT biology, cellular metabolism and preclinical metabolic models.',
  mechanism:'Research focuses on inhibition of nicotinamide N-methyltransferase (NNMT), an enzyme involved in nicotinamide and methyl-donor metabolism.',
  deeper:[{title:'Research overview',body:'Published work has examined NNMT inhibition in cells and animal metabolic models. It is important to keep that evidence separate from human clinical dosing claims.'},{title:'What is known in humans?',body:'This library does not encode an established human administration schedule. Custom tracking remains available without labeling it as a published human protocol.'},{title:'Why it is still here',body:'Users may track non-peptide research compounds alongside peptides. Classification is shown clearly rather than forcing everything into one category.'}]},
 {id:'ss-31',name:'SS-31 / Elamipretide',aliases:['ss31','ss-31','elamipretide','mmtp-131'],kind:'Mitochondria-targeting peptide',accent:'#18A0AE',referenceMode:'custom-only',
  summary:'SS-31, also called elamipretide, is a mitochondria-targeting peptide studied in several human clinical programs.',
  plainEnglish:'It is designed to interact with mitochondrial membranes, so researchers have explored whether it can influence cellular energy function in mitochondrial disease and other settings.',
  sources:[
   {id:'MMPOWER2-2020',title:'A randomized crossover trial of elamipretide in adults with primary mitochondrial myopathy',type:'Published randomized human clinical trial',url:'https://pubmed.ncbi.nlm.nih.gov/32096613/'},
   {id:'MMPOWER3-2023',title:'Efficacy and Safety of Elamipretide in Individuals With Primary Mitochondrial Myopathy: MMPOWER-3',type:'Published phase 3 randomized human clinical trial',url:'https://pubmed.ncbi.nlm.nih.gov/37268435/'},
   {id:'PROGRESSHF-2020',title:'Effects of Elamipretide on Left Ventricular Function in HFrEF: PROGRESS-HF',type:'Published phase 2 randomized human clinical trial',url:'https://pubmed.ncbi.nlm.nih.gov/32068002/'}
  ],evidence:'Published randomized human clinical research; study-specific schedules are not universal recommendations.',studiedFor:'Primary mitochondrial myopathy, Barth syndrome, cardiac and ophthalmic mitochondrial research settings.',
  mechanism:'Elamipretide is designed to associate with cardiolipin-rich mitochondrial inner membranes and influence mitochondrial structure and bioenergetics.',
  deeper:[
   {title:'Human research',body:'MMPOWER-2 randomized adults with primary mitochondrial myopathy to 40 mg/day subcutaneous elamipretide for 4 weeks in a crossover design. MMPOWER-3 studied 40 mg/day subcutaneously for 24 weeks. These are published study regimens tied to specific populations, not a universal starting plan.'},
   {title:'Dose-ranging context',body:'PROGRESS-HF randomized participants with heart failure with reduced ejection fraction to placebo, 4 mg, or 40 mg subcutaneous elamipretide once daily for 28 days. Neither elamipretide group significantly improved the primary ventricular-volume outcome versus placebo.'},
   {title:'Research limitations',body:'Clinical programs have produced mixed outcomes across indications. MMPOWER-3 did not demonstrate significant benefit on its primary endpoints in the overall genetically diverse primary mitochondrial myopathy population.'},
   {title:'Planning context',body:'School can show and model a published study regimen only with its population, route, duration and source attached. Community-style microgram ranges, fasting timing, reconstitution volumes and cycling conventions require independent sourcing before they are presented as reference data.'}
  ]},
 {id:'nad-plus',name:'NAD+',aliases:['nad','nad+','nicotinamide adenine dinucleotide'],kind:'Endogenous cofactor / metabolite',accent:'#7C5CFF',referenceMode:'custom-only',
  summary:'NAD+ is a naturally occurring cellular cofactor central to redox reactions and energy metabolism. It is not a peptide.',
  plainEnglish:'Cells use NAD+ as part of energy and repair chemistry. Research and commercial contexts can involve very different routes and formulations, so “NAD+” should never be treated as one universal protocol.',
  evidence:'Human research exists in route-specific contexts; no universal plan is encoded.',studiedFor:'Metabolism, aging biology, redox balance and pharmacokinetic questions in specific administration studies.',
  mechanism:'NAD+ participates in electron transfer and also serves as a substrate for enzymes including sirtuins and PARPs.',
  deeper:[{title:'Route matters',body:'Intravenous NAD+ research is not interchangeable with oral precursor research or other formulations. The app should always keep route/formulation context visible.'},{title:'Human evidence',body:'Human studies include pharmacokinetic and metabolomic work, but evidence is heterogeneous and should not be collapsed into a single recommended schedule.'},{title:'Tracker role',body:'The planner supports custom tracking so a user can organize a personally selected plan without the School page fabricating a universal reference.'}]},
 {id:'mots-c',name:'MOTS-c',aliases:['motsc','mots c','mitochondrial open reading frame of the 12s rrna-c'],kind:'Mitochondrial-derived peptide',accent:'#2FA9FF',referenceMode:'custom-only',
  summary:'MOTS-c is a mitochondrial-derived peptide studied for links between mitochondrial signaling, metabolism and exercise biology.',
  plainEnglish:'It is a small signal encoded by mitochondrial DNA. Human studies have measured endogenous MOTS-c biology, but that is different from having an established administered dosing schedule.',
  evidence:'Human biomarker/exercise research plus preclinical evidence; no established administered human schedule encoded.',studiedFor:'Exercise response, metabolic signaling, insulin sensitivity and aging-related mitochondrial biology.',
  mechanism:'Research suggests MOTS-c can participate in cellular stress and metabolic signaling, including pathways connected with AMPK and metabolic homeostasis.',
  deeper:[{title:'Human research',body:'Published human work includes circulating/endogenous MOTS-c observations and exercise-response studies. Those findings do not automatically define an exogenous administration plan.'},{title:'Preclinical research',body:'A substantial portion of the mechanistic and intervention literature remains preclinical. This library keeps that distinction visible.'},{title:'Planning context',body:'Custom-plan tools remain available, but the app labels the plan as user-created unless a route-matched human reference is deliberately added later.'}]}
];

export const deepSectionLabels=['Research overview','How it works — deeper dive','Human evidence','Preclinical evidence','Key studies','Safety & limitations','Reference context','Sources'];
