import React,{useState} from 'react';
import {ScrollView,Text,Pressable,View,StyleSheet} from 'react-native';
import type {Store} from './engine';
import {prettyDate,prettyTime,scheduleSummary,stageAmount} from './engine';
import {getActivePlans,planDashboard,inventorySummary} from './multiplan-v04';
import {archivePlan} from './plan-actions-v04';
import {Button,Card,u} from './ui';
export default function MyPlans({store,update,onOpen,onEdit,onHistory,onDraft,onGuide,inventory=false}:{store:Store;update:(f:(s:Store)=>Store)=>Promise<void>;onOpen:(id:string)=>void;onEdit:(id:string,section?:string)=>void;onHistory:(id:string)=>void;onDraft:()=>void;onGuide:()=>void;inventory?:boolean}){
 const [confirm,setConfirm]=useState<string|null>(null),[error,setError]=useState(''),[view,setView]=useState<'active'|'supply'|'archived'>('active');
 const plans=getActivePlans(store),supplyPlans=plans.filter(plan=>{if(plan.inventoryTracking===false)return false;const coverage=inventorySummary(plan).coverage;return coverage.supply===null||(coverage.vials!==null&&coverage.vials<=.25)||coverage.enough===false;}),shown=view==='supply'?supplyPlans:plans;
 return <ScrollView contentContainerStyle={u.scroll}><Text style={u.title}>{inventory?'Inventory':'My Peptides'}</Text><Text style={u.body}>{plans.length} active {plans.length===1?'plan':'plans'} · each keeps its own stages, schedule, vial setup, supply and history.</Text>
 {!inventory&&<View style={s.filters}>{([{key:'active',label:'Active',count:plans.length},{key:'supply',label:'Supply',count:supplyPlans.length},{key:'archived',label:'Archived',count:store.archives.length}] as const).map(item=><Pressable key={item.key} accessibilityRole="tab" accessibilityState={{selected:view===item.key}} onPress={()=>setView(item.key)} style={[s.filter,view===item.key&&s.filterSelected]}><Text style={[s.filterCount,view===item.key&&s.filterTextSelected]}>{item.count}</Text><Text style={[s.filterLabel,view===item.key&&s.filterTextSelected]}>{item.label}</Text></Pressable>)}</View>}
 {inventory&&<Text style={u.small}>View remaining vial inventory and update each peptide when supply changes.</Text>}
 {!!error&&<Text style={u.error}>{error}</Text>}
 {store.draft&&<Card><Text style={u.heading}>Continue your draft</Text><Text style={u.body}>{store.draft.compoundName} · not started</Text><Button label="Continue draft" onPress={onDraft}/></Card>}
 {view!=='archived'&&planDashboard([...shown].reverse()).map(({plan,progress,next})=>{const supply=inventorySummary(plan),lastLogged=[...plan.events].filter(e=>e.status==='completed'||e.status==='skipped').sort((a,b)=>(b.completedAt||b.skippedAt||b.scheduledAt).localeCompare(a.completedAt||a.skippedAt||a.scheduledAt))[0],week=progress.started?Math.max(1,Math.ceil(progress.day/7)):null;return <Card key={plan.id}>
  <View style={s.top}><View style={{flex:1}}><Text style={u.heading}>{plan.compoundName}</Text><Text style={u.small}>{!progress.started?'Starts '+prettyDate(plan.startDate):progress.inBreak?'Planned break':progress.ended?'Scheduled stages complete':'Day '+progress.day+' of '+progress.totalDays}</Text></View><View style={s.active}><Text style={s.activeText}>{plan.pausedAt?'PAUSED':'ACTIVE'}</Text></View></View>
  <View style={s.timeline}><View><Text style={s.factLabel}>STARTED</Text><Text style={s.timelineValue}>{prettyDate(plan.startDate)}</Text></View><View style={s.timelineDivider}/><View><Text style={s.factLabel}>TIME ON PLAN</Text><Text style={s.timelineValue}>{week?'Week '+week+' · Day '+progress.day:'Not started'}</Text></View></View>
  {progress.stageIndex>=0&&<Text style={u.small}>Stage {progress.stageIndex+1} · {stageAmount(plan.stages[progress.stageIndex])}</Text>}<Text style={u.small}>{plan.vialMg} mg vial · {plan.waterMl} mL diluent · {plan.syringeCapacityUnits?plan.syringeCapacityUnits+' U syringe':'Automatic syringe size'}</Text><View style={s.factGrid}><View style={s.fact}><Text style={s.factLabel}>LAST ACTIVITY</Text><Text style={s.factValue}>{lastLogged?(lastLogged.status==='completed'?'Taken · ':'Skipped · ')+prettyDate(lastLogged.localDate):'Nothing logged yet'}</Text></View><View style={s.fact}><Text style={s.factLabel}>NEXT</Text><Text style={s.factValue}>{next?prettyDate(next.localDate)+' · '+prettyTime(next.scheduledAt):'No upcoming event'}</Text></View><View style={s.fact}><Text style={s.factLabel}>SCHEDULE</Text><Text style={s.factValue}>{scheduleSummary(plan.stages[progress.stageIndex]?.override||plan.defaultSchedule)}</Text></View><View style={s.fact}><Text style={s.factLabel}>SUPPLY</Text><Text style={s.factValue}>{plan.inventoryTracking===false?'Tracking off':supply.coverage.supply===null?'Add starting inventory':Number(supply.coverage.vials!.toFixed(2))+' vial equivalents'}</Text></View>{plan.inventoryTracking!==false&&<View style={s.inventoryStrip}><View style={s.vialRow}>{supply.coverage.vials===null?<View style={[s.miniVial,{opacity:.35}]}/>:Array.from({length:Math.min(6,Math.max(1,Math.ceil(Math.max(0,supply.coverage.vials))))},(_,i)=>{const fill=Math.min(1,Math.max(0,supply.coverage.vials!-i));return <View key={i} style={s.miniVial}><View style={[s.miniVialFill,{height:4+18*fill}]}/></View>;})}</View><Pressable accessibilityRole="button" accessibilityLabel={'Add inventory for '+plan.compoundName} onPress={()=>onEdit(plan.id,'Inventory')}><Text style={u.link}>+ Add inventory</Text></Pressable></View>}<View style={s.fact}><Text style={s.factLabel}>PROGRESS</Text><Text style={s.factValue}>{progress.completed} / {progress.total} completed</Text></View></View>
  <View style={s.actions}><Pressable accessibilityRole="button" accessibilityLabel={'View '+plan.compoundName+' plan'} onPress={()=>onOpen(plan.id)} style={s.primary}><Text style={s.primaryText}>View</Text></Pressable><Pressable accessibilityRole="button" accessibilityLabel={'Edit '+plan.compoundName+' plan'} onPress={()=>onEdit(plan.id)} style={s.secondary}><Text style={s.secondaryText}>Edit</Text></Pressable><Pressable accessibilityRole="button" accessibilityLabel={'History for '+plan.compoundName} onPress={()=>onHistory(plan.id)} style={s.secondary}><Text style={s.secondaryText}>History</Text></Pressable></View>

  {confirm===plan.id?<><Text style={u.small}>Archive this plan? It will leave Today and Calendar. Its saved history is retained.</Text><Button label={'Confirm archive '+plan.compoundName} secondary onPress={()=>update(s=>archivePlan(s,plan.id)).then(()=>setConfirm(null)).catch(e=>setError(String(e)))}/><Button label="Keep active" secondary onPress={()=>setConfirm(null)}/></>:<Pressable accessibilityRole="button" accessibilityLabel={'Archive '+plan.compoundName} onPress={()=>setConfirm(plan.id)}><Text style={[u.link,{textAlign:'center'}]}>Archive plan</Text></Pressable>}
 </Card>})}
 {view==='supply'&&!supplyPlans.length&&<Card><Text style={u.heading}>Supply looks covered</Text><Text style={u.body}>No active peptide currently has missing or insufficient inventory.</Text></Card>}
 {view==='archived'&&[...store.archives].reverse().map(plan=>{const logged=plan.events.filter(e=>e.status==='completed'||e.status==='skipped'),last=[...logged].sort((a,b)=>(b.completedAt||b.skippedAt||b.scheduledAt).localeCompare(a.completedAt||a.skippedAt||a.scheduledAt))[0];return <Card key={plan.id}><View style={s.top}><View style={{flex:1}}><Text style={u.heading}>{plan.compoundName}</Text><Text style={u.small}>{logged.length} history {logged.length===1?'entry':'entries'} · started {prettyDate(plan.startDate)}</Text></View><View style={s.archived}><Text style={s.archivedText}>ARCHIVED</Text></View></View><View style={s.timeline}><View><Text style={s.factLabel}>LAST ACTIVITY</Text><Text style={s.timelineValue}>{last?prettyDate(last.localDate):'No saved activity'}</Text></View><View style={s.timelineDivider}/><View><Text style={s.factLabel}>LAST DOSE</Text><Text style={s.timelineValue}>{last?stageAmount({amountMg:String(last.amountMg),amountUnit:last.amountUnit}):'Not available'}</Text></View></View><Pressable accessibilityRole="button" accessibilityLabel={'History for archived '+plan.compoundName} onPress={()=>onHistory(plan.id)} style={s.primary}><Text style={s.primaryText}>View history</Text></Pressable></Card>;})}
 {view==='archived'&&!store.archives.length&&<Card><Text style={u.body}>Archived peptides will appear here with their saved history.</Text></Card>}
 {view==='active'&&!plans.length&&<Card><Text style={u.body}>Your active plans will appear here. Learn in Pep School, then build a plan in Guide.</Text></Card>}
 {view!=='archived'&&<Button label="Add another plan" onPress={onGuide}/>}
 </ScrollView>;
}
const s=StyleSheet.create({filters:{flexDirection:'row',gap:7,marginTop:16,marginBottom:4},filter:{flex:1,minHeight:62,alignItems:'center',justifyContent:'center',borderRadius:15,backgroundColor:'#f2f6fc',borderWidth:1,borderColor:'#e0e9f4'},filterSelected:{backgroundColor:'#dff6ff',borderColor:'#19b3e3'},filterCount:{fontSize:18,fontWeight:'800',color:'#667597'},filterLabel:{fontSize:10,fontWeight:'800',color:'#667597',marginTop:2},filterTextSelected:{color:'#10204a'},archived:{backgroundColor:'#f1eff8',borderRadius:10,paddingHorizontal:8,paddingVertical:5},archivedText:{fontSize:10,fontWeight:'800',color:'#68578f'},timeline:{flexDirection:'row',alignItems:'center',gap:14,marginTop:10,marginBottom:10,padding:12,borderRadius:14,backgroundColor:'#eef9fd'},timelineDivider:{width:1,height:32,backgroundColor:'#cfe5ee'},timelineValue:{fontSize:13,lineHeight:18,fontWeight:'800',color:'#10204a',marginTop:3},top:{flexDirection:'row',alignItems:'flex-start',gap:10},active:{backgroundColor:'#eaf8f1',borderRadius:10,paddingHorizontal:8,paddingVertical:5},activeText:{fontSize:10,fontWeight:'800',color:'#178066'},inventoryStrip:{width:'100%',flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:10,paddingVertical:8,borderRadius:12,backgroundColor:'#f3fbff'},vialRow:{flexDirection:'row',gap:4,alignItems:'flex-end'},miniVial:{width:15,height:28,borderWidth:1.5,borderColor:'#8c4bc1',borderRadius:4,overflow:'hidden',justifyContent:'flex-end',backgroundColor:'#faf6ff'},miniVialFill:{width:'100%',backgroundColor:'#bd65df'},factGrid:{flexDirection:'row',flexWrap:'wrap',gap:8,marginTop:12},fact:{width:'48%',minWidth:0,padding:10,borderRadius:12,backgroundColor:'#f7faff'},factLabel:{fontSize:9,fontWeight:'800',letterSpacing:1,color:'#667597'},factValue:{fontSize:12,lineHeight:17,fontWeight:'700',color:'#10204a',marginTop:4},actions:{flexDirection:'row',gap:8,marginTop:12},primary:{flex:1,alignItems:'center',paddingVertical:11,borderRadius:12,backgroundColor:'#21b6e8'},primaryText:{fontWeight:'800',color:'#fff'},secondary:{minWidth:88,alignItems:'center',paddingVertical:11,paddingHorizontal:16,borderRadius:12,backgroundColor:'#eef8fc',borderWidth:1,borderColor:'#d9e8f2'},secondaryText:{fontWeight:'800',color:'#10204a'}});
