import React,{useState} from 'react';
import {Text,Pressable,View,StyleSheet} from 'react-native';
import {Card,u} from './ui';
import {reconstitutionBasics} from './school-basics';
export default function QuickStart(){
 const [open,setOpen]=useState(false);
 return <Card><Text style={u.heading}>Quick Start</Text><Text style={u.body}>New to vials and calculations? Start with the words, then the numbers.</Text>
 <Text style={u.small}>Freeze-dried powder + the correct liquid → a solution with a known concentration.</Text>
 <Pressable accessibilityRole="button" accessibilityLabel="Quick Start — Learn More" accessibilityState={{expanded:open}} onPress={()=>setOpen(!open)}><Text style={u.link}>{open?'Show less':'Learn More'} {open?'−':'+'}</Text></Pressable>
 {open&&<View>{reconstitutionBasics.details.map((text,i)=><View key={text} style={{marginTop:12}}><Text style={u.heading}>{['What is in the vial?','What is reconstitution?','What is bacteriostatic water?','Use the correct diluent','The math at a glance','Why volume changes the draw'][i]}</Text><Text style={u.body}>{text}</Text></View>)}<Text style={[u.heading,{marginTop:16}]}>Why values may be pre-filled</Text><Text style={u.body}>A reference may supply plan values. Some references also have a separately labelled Common Research Setup for the calculator. These are different sources: check the labels and confirm your vial and diluent. Editable setup defaults are not a clinical recommendation.</Text><Text style={u.small}>Reference labels: {reconstitutionBasics.sourceLabels.join(' · ')}</Text></View>}
 </Card>;
}

export function LearningPaths(){
 const paths=[
  {id:'foundations',title:'PepPlan Foundations',tag:'START HERE',summary:'Learn the vocabulary, evidence labels and calculation concepts used throughout PepPlan.',lessons:['What peptides are — and are not','Understanding evidence levels','Route and formulation matter','mg, mcg, mL and syringe units','How to read a Pep School profile']},
  {id:'planning',title:'Planning Fundamentals',tag:'GUIDE & TRACK',summary:'Understand how a reference becomes an editable model and a daily timeline.',lessons:['Individual vials versus kits','Stages, schedules and planned breaks','Concentration and draw calculations','Using Today, Calendar and History','Why logged events preserve historical truth']},
  {id:'research',title:'Research Literacy',tag:'DEEPER LEARNING',summary:'Build confidence reading studies without treating every source as equally authoritative.',lessons:['Human versus preclinical evidence','Population, route and formulation','Reading key findings and limitations','Recognizing unsupported claims','Conflicting and negative evidence']},
 ] as const;
 const [open,setOpen]=useState<string|null>(null);
 return <View style={s.paths}><View style={s.pathHeader}><View><Text style={s.eyebrow}>LEARN PEPPLAN</Text><Text style={s.pathTitle}>Short learning paths</Text></View><Text style={s.courseCount}>3 courses</Text></View><Text style={u.small}>Practical lessons that make School, Guide and Today easier to use.</Text>{paths.map(path=>{const expanded=open===path.id;return <View key={path.id} style={s.course}><Pressable accessibilityRole="button" accessibilityLabel={path.title} accessibilityState={{expanded}} onPress={()=>setOpen(expanded?null:path.id)} style={s.courseTop}><View style={{flex:1}}><Text style={s.tag}>{path.tag}</Text><Text style={s.courseTitle}>{path.title}</Text><Text style={s.courseSummary}>{path.summary}</Text><View style={s.progress}><View style={s.progressFill}/></View><Text style={s.progressText}>Preview · {path.lessons.length} lessons</Text></View><Text style={s.chevron}>{expanded?'−':'+'}</Text></Pressable>{expanded&&<View style={s.lessons}>{path.lessons.map((lesson,index)=><View key={lesson} style={s.lesson}><View style={s.lessonNumber}><Text style={s.lessonNumberText}>{index+1}</Text></View><Text style={s.lessonText}>{lesson}</Text></View>)}<Text style={s.coming}>Course progress will be saved when the learning player is connected.</Text></View>}</View>})}</View>;
}
const s=StyleSheet.create({paths:{marginTop:16},pathHeader:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-end'},eyebrow:{fontSize:10,fontWeight:'800',letterSpacing:1.3,color:'#7557f6'},pathTitle:{fontSize:21,fontWeight:'800',color:'#0e1c4a',marginTop:4},courseCount:{fontSize:11,fontWeight:'700',color:'#667597'},course:{marginTop:10,borderWidth:1,borderColor:'#dde8f6',borderRadius:18,backgroundColor:'#fff',overflow:'hidden'},courseTop:{flexDirection:'row',gap:10,padding:14},tag:{fontSize:9,fontWeight:'800',letterSpacing:1,color:'#168bb8'},courseTitle:{fontSize:16,fontWeight:'800',color:'#0e1c4a',marginTop:4},courseSummary:{fontSize:12,lineHeight:17,color:'#667597',marginTop:4},progress:{height:5,borderRadius:3,backgroundColor:'#edf2f8',marginTop:10,overflow:'hidden'},progressFill:{width:'8%',height:'100%',backgroundColor:'#27b9ee'},progressText:{fontSize:10,color:'#667597',marginTop:5},chevron:{fontSize:23,color:'#27a8d8'},lessons:{paddingHorizontal:14,paddingBottom:14},lesson:{flexDirection:'row',alignItems:'center',gap:9,paddingVertical:8,borderTopWidth:StyleSheet.hairlineWidth,borderTopColor:'#e2eaf4'},lessonNumber:{width:24,height:24,borderRadius:12,alignItems:'center',justifyContent:'center',backgroundColor:'#eaf9ff'},lessonNumberText:{fontSize:10,fontWeight:'800',color:'#126e95'},lessonText:{flex:1,fontSize:12,fontWeight:'700',color:'#34456c'},coming:{fontSize:10,lineHeight:15,color:'#7557f6',marginTop:8}});
