import {stageDuration,stageDays,durationLabel,durationPatch} from './duration';
import React,{useState}from'react';import{View,Text,Pressable,StyleSheet}from'react-native';
import type{Stage,Schedule}from'./engine';import{stageAmount,displayedAmount,storedAmount,scheduleSummary,addDays,parseDate,prettyDate}from'./engine';import{Field,u,C}from'./ui';
export default function StageCard({stage,index,previousDays,startDate,schedule,last,edit,changeSchedule,useDefault}:{stage:Stage;index:number;previousDays:number;startDate:string;schedule:Schedule|null;last:boolean;edit?:(patch:Partial<Stage>)=>void;changeSchedule?:()=>void;useDefault?:()=>void}){
 const [editing,setEditing]=useState(false);const color=[C.blue,C.purple,'#29a5ab'][index%3];const duration=stageDuration(stage),days=stageDays(stage);const start=parseDate(startDate)&&Number.isFinite(previousDays)&&Number.isFinite(days)?addDays(startDate,previousDays):null;
 return <View style={s.row}><View style={s.rail}><View style={[s.dot,{backgroundColor:color}]}><Text style={s.number}>{index+1}</Text></View>{!last&&<View style={[s.line,{backgroundColor:color+'55'}]}/>}</View><View style={[s.card,{borderTopColor:color}]}>
 <Text style={[u.label,{color}]}>STAGE {index+1}</Text><Text style={u.small}>{durationLabel(stage)}</Text>
 <Text testID={'stage-amount-'+index} style={s.amount}>{stageAmount(stage)}</Text><Text style={u.body}>{start?prettyDate(start)+' → '+prettyDate(addDays(start,days-1)):'Choose a start date to see stage dates'}</Text>
 {edit&&<Pressable accessibilityRole="button" accessibilityLabel={'Edit stage '+(index+1)} onPress={()=>setEditing(!editing)}><Text style={u.link}>{editing?'Done':'Change amount / duration ›'}</Text></Pressable>}
 {edit&&editing&&<><Field label={'Stage '+(index+1)+' amount'} value={displayedAmount(stage)} numeric placeholder={'Choose '+(stage.amountUnit||'mg')} onChange={v=>edit({amountMg:storedAmount(v,stage.amountUnit)})}/><View style={u.row}>{(['mg','mcg'] as const).map(unit=><Pressable key={unit} accessibilityRole="radio" accessibilityLabel={'Stage '+(index+1)+' unit '+unit} accessibilityState={{checked:stage.amountUnit===unit}} aria-checked={stage.amountUnit===unit} onPress={()=>edit({amountUnit:unit})} style={[u.pill,stage.amountUnit===unit&&u.selected]}><Text style={u.body}>{unit}</Text></Pressable>)}</View><Field label={'Stage '+(index+1)+' duration'} value={duration.value} numeric placeholder="Choose duration" onChange={v=>edit(durationPatch(v,duration.unit))}/><View style={u.row}>{(['days','weeks'] as const).map(unit=><Pressable key={unit} accessibilityRole="radio" accessibilityLabel={'Stage '+(index+1)+' duration '+unit} accessibilityState={{checked:duration.unit===unit}} aria-checked={duration.unit===unit} onPress={()=>edit(durationPatch(duration.value,unit))} style={[u.pill,duration.unit===unit&&u.selected]}><Text style={u.body}>{unit==='days'?'Days':'Weeks'}</Text></Pressable>)}</View></>}
 <View style={s.schedule}><Text style={u.label}>SCHEDULE</Text><Text style={u.body}>{scheduleSummary(stage.override||schedule)}</Text>{stage.override&&<Text style={u.small}>Stage-specific schedule</Text>}{changeSchedule&&<Pressable accessibilityRole="button" accessibilityLabel={'Change stage '+(index+1)+' schedule'} onPress={changeSchedule}><Text style={u.link}>Change schedule ›</Text></Pressable>}{stage.override&&useDefault&&<Pressable accessibilityRole="button" accessibilityLabel={'Use plan default for stage '+(index+1)} onPress={useDefault}><Text style={u.link}>Use plan default</Text></Pressable>}</View>
 </View></View>;
}
const s=StyleSheet.create({row:{flexDirection:'row',marginTop:16},rail:{width:30,alignItems:'center'},dot:{width:28,height:28,borderRadius:14,alignItems:'center',justifyContent:'center'},number:{color:'#fff',fontWeight:'800'},line:{width:3,flex:1,marginTop:6,marginBottom:-10},card:{flex:1,minWidth:0,marginLeft:10,borderRadius:22,borderWidth:1,borderColor:C.border,borderTopWidth:3,padding:16,backgroundColor:'#fff'},amount:{fontSize:30,lineHeight:38,fontWeight:'800',color:C.ink,marginTop:8},schedule:{marginTop:14,paddingTop:12,borderTopWidth:1,borderColor:C.border}});
