import React from 'react';
import {Text,View,Pressable,TextInput,StyleSheet} from 'react-native';
export const C={ink:'#10204a',muted:'#61728f',blue:'#13ace0',purple:'#7557f6',border:'#dce7f5',pale:'#eefaff'};
export function Button({label,onPress,secondary=false,disabled=false,accessibilityLabel}:{accessibilityLabel?:string;label:string;onPress:()=>void;secondary?:boolean;disabled?:boolean}){return <Pressable accessibilityRole="button" accessibilityLabel={accessibilityLabel??label} disabled={disabled} onPress={onPress} style={[u.button,secondary&&u.secondary,disabled&&{opacity:.4}]}><Text style={[u.buttonText,secondary&&{color:C.ink}]}>{label}</Text></Pressable>;}
export function Field({label,value,onChange,placeholder='Choose…',numeric=false,editable=true}:{label:string;value:string;onChange:(v:string)=>void;placeholder?:string;numeric?:boolean;editable?:boolean}){return <View style={u.field}><Text style={u.label}>{label}</Text><TextInput accessibilityLabel={label} value={value} onChangeText={onChange} placeholder={placeholder} keyboardType={numeric?'decimal-pad':'default'} style={u.input} editable={editable}/></View>;}
export function Card({children}:{children:React.ReactNode}){return <View style={u.card}>{children}</View>;}
export function Evidence({kind,text}:{kind:string;text?:string}){
 const approved=/approved/i.test(kind),human=/human clinical/i.test(kind),common=/common research/i.test(kind),blend=/blend/i.test(kind),user=/user|customized/i.test(kind);
 const color=approved?'#087d85':human?'#2459b4':common?'#94600a':blend?'#7d479d':user?'#536176':'#6346ae';
 const title=/US FDA/i.test(kind)?'US FDA · PRODUCT-SPECIFIC EVIDENCE':approved?'APPROVED CANADIAN LABELING':human?'PUBLISHED HUMAN CLINICAL RESEARCH':common?'COMMON RESEARCH PRACTICE':blend?'BLEND — COMPONENT EVIDENCE ONLY':user?'USER-CREATED PLAN':'PUBLISHED RESEARCH / PRECLINICAL / MECHANISTIC';
 return <View style={[u.evidence,{borderLeftColor:color}]}><Text style={[u.label,{color}]}>{title}</Text>{text&&<Text style={u.body}>{text}</Text>}{common&&<Text style={u.small}>Reference information — not an established human clinical dosing schedule.</Text>}</View>;
}
export const u=StyleSheet.create({scroll:{padding:20,paddingBottom:40},title:{fontSize:29,fontWeight:'800',color:C.ink,marginBottom:8},heading:{fontSize:18,fontWeight:'800',color:C.ink,marginBottom:8},body:{fontSize:14,lineHeight:22,color:C.muted},small:{fontSize:12,lineHeight:18,color:C.muted,marginTop:6},label:{fontSize:12,fontWeight:'800',color:C.muted,marginBottom:5},card:{backgroundColor:'#fff',borderWidth:1,borderColor:C.border,borderRadius:22,padding:16,marginTop:14},field:{marginTop:12},input:{borderWidth:1,borderColor:C.border,borderRadius:12,padding:12,minHeight:46,fontSize:16,color:C.ink,backgroundColor:'#fff'},button:{minHeight:50,borderRadius:16,backgroundColor:C.blue,alignItems:'center',justifyContent:'center',padding:12,marginTop:14},secondary:{backgroundColor:C.pale,borderWidth:1,borderColor:C.border},buttonText:{fontSize:15,fontWeight:'800',color:'#fff',textAlign:'center'},row:{flexDirection:'row',gap:10,alignItems:'center',flexWrap:'wrap'},link:{color:'#067da7',fontSize:14,fontWeight:'700',paddingVertical:12},evidence:{borderLeftWidth:4,borderRadius:14,padding:12,backgroundColor:'#f5f8fc',marginTop:12},error:{color:'#a82a40',fontSize:13,lineHeight:20,marginTop:10},pill:{paddingHorizontal:12,paddingVertical:10,borderRadius:12,backgroundColor:'#f2f6fc',margin:3},selected:{backgroundColor:'#d8f2ff',borderWidth:1,borderColor:C.blue}});
